[package]
name = "echo-http"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.135"
tokio = { version = "1", features = ["full"] }
# reqwest = { version = "0.12", features = ["json"], default-features = false }
# serde = { version = "1.0", features = ["derive"], optional = true }
# serde_json = { version = "1.0", optional = true } 
# tokio = { version = "1", features = ["full"] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "main"
path = "src/main.rs"

# [features]
# default = []
# json = ["serde", "serde_json"]
